#!/usr/bin/env ruby
require 'optparse'
require_relative '../config/environment'

log_out = STDOUT

opt = OptionParser.new
opt.on('-l LOGFILE') do |logfile|
  log_out = logfile
end
opt.parse!(ARGV)

logger = Logger.new(log_out)
Rails.logger = logger

while true
  begin
    logger.debug '========== Start loop =========='
    EscalationQueue.process
    NotificationQueue.process
  rescue => err
    backtrace = err.backtrace.join("\n")
    logger.error "#{err}\n#{backtrace}"
  end

  sleep 10
end

