#!/usr/bin/env ruby
require 'optparse'
require_relative '../config/environment'

log_out = STDOUT

opt = OptionParser.new
opt.on('-l LOGFILE') do |logfile|
  log_out = logfile
end
opt.parse!(ARGV)

logger = Logger.new(log_out)
Rails.logger = logger

watchers = []

while true
  logger.debug "==== Loading providers ===="
  watchers.each do |watcher|
    begin
      watcher.provider.reload
    rescue ActiveRecord::RecordNotFound
      watcher.stop
      logger.info "#{watcher} stopped"
    end
  end

  # add new watchers
  Provider.all.each do |provider|
    watcher = watchers.find do |w|
      w.provider == provider
    end
    next if watcher

    watcher = provider.watcher
    next unless watcher

    logger.debug "New provider: #{provider.inspect}"
    watchers << watcher
    Thread.start(watcher) do |w|
      begin
        w.start
        logger.debug "#{w} finished."
      rescue Exception => err
        backtrace = err.backtrace.join("\n")
        logger.error "#{err}\n#{backtrace}"
      ensure
        watchers.delete(w)
      end
    end
    logger.info "#{watcher} started"
  end

  sleep 60
end

