require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe EscalationSeriesController, :type => :controller do

  # This should return the minimal set of attributes required to create a valid
  # EscalationSeries. As you add validations to EscalationSeries, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # EscalationSeriesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all escalation_series as @escalation_series" do
      escalation_series = EscalationSeries.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:escalation_series)).to eq([escalation_series])
    end
  end

  describe "GET show" do
    it "assigns the requested escalation_series as @escalation_series" do
      escalation_series = EscalationSeries.create! valid_attributes
      get :show, {:id => escalation_series.to_param}, valid_session
      expect(assigns(:escalation_series)).to eq(escalation_series)
    end
  end

  describe "GET new" do
    it "assigns a new escalation_series as @escalation_series" do
      get :new, {}, valid_session
      expect(assigns(:escalation_series)).to be_a_new(EscalationSeries)
    end
  end

  describe "GET edit" do
    it "assigns the requested escalation_series as @escalation_series" do
      escalation_series = EscalationSeries.create! valid_attributes
      get :edit, {:id => escalation_series.to_param}, valid_session
      expect(assigns(:escalation_series)).to eq(escalation_series)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new EscalationSeries" do
        expect {
          post :create, {:escalation_series => valid_attributes}, valid_session
        }.to change(EscalationSeries, :count).by(1)
      end

      it "assigns a newly created escalation_series as @escalation_series" do
        post :create, {:escalation_series => valid_attributes}, valid_session
        expect(assigns(:escalation_series)).to be_a(EscalationSeries)
        expect(assigns(:escalation_series)).to be_persisted
      end

      it "redirects to the created escalation_series" do
        post :create, {:escalation_series => valid_attributes}, valid_session
        expect(response).to redirect_to(EscalationSeries.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved escalation_series as @escalation_series" do
        post :create, {:escalation_series => invalid_attributes}, valid_session
        expect(assigns(:escalation_series)).to be_a_new(EscalationSeries)
      end

      it "re-renders the 'new' template" do
        post :create, {:escalation_series => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested escalation_series" do
        escalation_series = EscalationSeries.create! valid_attributes
        put :update, {:id => escalation_series.to_param, :escalation_series => new_attributes}, valid_session
        escalation_series.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested escalation_series as @escalation_series" do
        escalation_series = EscalationSeries.create! valid_attributes
        put :update, {:id => escalation_series.to_param, :escalation_series => valid_attributes}, valid_session
        expect(assigns(:escalation_series)).to eq(escalation_series)
      end

      it "redirects to the escalation_series" do
        escalation_series = EscalationSeries.create! valid_attributes
        put :update, {:id => escalation_series.to_param, :escalation_series => valid_attributes}, valid_session
        expect(response).to redirect_to(escalation_series)
      end
    end

    describe "with invalid params" do
      it "assigns the escalation_series as @escalation_series" do
        escalation_series = EscalationSeries.create! valid_attributes
        put :update, {:id => escalation_series.to_param, :escalation_series => invalid_attributes}, valid_session
        expect(assigns(:escalation_series)).to eq(escalation_series)
      end

      it "re-renders the 'edit' template" do
        escalation_series = EscalationSeries.create! valid_attributes
        put :update, {:id => escalation_series.to_param, :escalation_series => invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested escalation_series" do
      escalation_series = EscalationSeries.create! valid_attributes
      expect {
        delete :destroy, {:id => escalation_series.to_param}, valid_session
      }.to change(EscalationSeries, :count).by(-1)
    end

    it "redirects to the escalation_series list" do
      escalation_series = EscalationSeries.create! valid_attributes
      delete :destroy, {:id => escalation_series.to_param}, valid_session
      expect(response).to redirect_to(escalation_series_index_url)
    end
  end

end
