require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe NotifierProvidersController, :type => :controller do

  # This should return the minimal set of attributes required to create a valid
  # NotifierProvider. As you add validations to NotifierProvider, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # NotifierProvidersController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all notifier_providers as @notifier_providers" do
      notifier_provider = NotifierProvider.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:notifier_providers)).to eq([notifier_provider])
    end
  end

  describe "GET show" do
    it "assigns the requested notifier_provider as @notifier_provider" do
      notifier_provider = NotifierProvider.create! valid_attributes
      get :show, {:id => notifier_provider.to_param}, valid_session
      expect(assigns(:notifier_provider)).to eq(notifier_provider)
    end
  end

  describe "GET new" do
    it "assigns a new notifier_provider as @notifier_provider" do
      get :new, {}, valid_session
      expect(assigns(:notifier_provider)).to be_a_new(NotifierProvider)
    end
  end

  describe "GET edit" do
    it "assigns the requested notifier_provider as @notifier_provider" do
      notifier_provider = NotifierProvider.create! valid_attributes
      get :edit, {:id => notifier_provider.to_param}, valid_session
      expect(assigns(:notifier_provider)).to eq(notifier_provider)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new NotifierProvider" do
        expect {
          post :create, {:notifier_provider => valid_attributes}, valid_session
        }.to change(NotifierProvider, :count).by(1)
      end

      it "assigns a newly created notifier_provider as @notifier_provider" do
        post :create, {:notifier_provider => valid_attributes}, valid_session
        expect(assigns(:notifier_provider)).to be_a(NotifierProvider)
        expect(assigns(:notifier_provider)).to be_persisted
      end

      it "redirects to the created notifier_provider" do
        post :create, {:notifier_provider => valid_attributes}, valid_session
        expect(response).to redirect_to(NotifierProvider.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved notifier_provider as @notifier_provider" do
        post :create, {:notifier_provider => invalid_attributes}, valid_session
        expect(assigns(:notifier_provider)).to be_a_new(NotifierProvider)
      end

      it "re-renders the 'new' template" do
        post :create, {:notifier_provider => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested notifier_provider" do
        notifier_provider = NotifierProvider.create! valid_attributes
        put :update, {:id => notifier_provider.to_param, :notifier_provider => new_attributes}, valid_session
        notifier_provider.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested notifier_provider as @notifier_provider" do
        notifier_provider = NotifierProvider.create! valid_attributes
        put :update, {:id => notifier_provider.to_param, :notifier_provider => valid_attributes}, valid_session
        expect(assigns(:notifier_provider)).to eq(notifier_provider)
      end

      it "redirects to the notifier_provider" do
        notifier_provider = NotifierProvider.create! valid_attributes
        put :update, {:id => notifier_provider.to_param, :notifier_provider => valid_attributes}, valid_session
        expect(response).to redirect_to(notifier_provider)
      end
    end

    describe "with invalid params" do
      it "assigns the notifier_provider as @notifier_provider" do
        notifier_provider = NotifierProvider.create! valid_attributes
        put :update, {:id => notifier_provider.to_param, :notifier_provider => invalid_attributes}, valid_session
        expect(assigns(:notifier_provider)).to eq(notifier_provider)
      end

      it "re-renders the 'edit' template" do
        notifier_provider = NotifierProvider.create! valid_attributes
        put :update, {:id => notifier_provider.to_param, :notifier_provider => invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested notifier_provider" do
      notifier_provider = NotifierProvider.create! valid_attributes
      expect {
        delete :destroy, {:id => notifier_provider.to_param}, valid_session
      }.to change(NotifierProvider, :count).by(-1)
    end

    it "redirects to the notifier_providers list" do
      notifier_provider = NotifierProvider.create! valid_attributes
      delete :destroy, {:id => notifier_provider.to_param}, valid_session
      expect(response).to redirect_to(notifier_providers_url)
    end
  end

end
